language: java
jdk:
  - openjdk8

branches:  # Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정, 현재 옵션은 오직 master 브랜치에 push될 때만 수행
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:  # 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_deploy: # deploy명렁어가 실행되기 전에 수행, CodeDeploy는 Jar 파일은 인식하지 못하므로 Jar+기타 설정 파일들을 모아 압축(zip)함
  - zip -r song_ex1 * #현재 위치의 모든 파일을 song_ex1 으로 압축, 명령어의 마지막 위치는 본인의 프로젝트 이름이어야 함
  - mkdir -p deploy # deploy라는 디렉토리를 Travis CI가 실행 중인 위치에서 생성
  - mv song_ex1.zip deploy/song_ex1.zip # song_ex1.zip 파일을 deploy/song_ex1.zip으로 이동

deploy: # S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settiongs에 설정된 값
    bucket: springboot2-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 # 앞에서 생성한 deploy 디렉토리를 지정, 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true



script: "./gradlew clean build"
#master브랜치에 푸시되었을 때 수행하는 명령어, 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행

#CI 실행 완료 시 메일로 알람
notifications: # Travis CI 실행 완료 시 자동으로 알람이 가도록 설정
  email:
    recipients:
      - car0628@naver.com



